#theme: jekyll-theme-slate
#theme: minima
#remote_theme: "daattali/beautiful-jekyll"
remote_theme: "Gaohaoyang/gaohaoyang.github.io"

# not needed ?
url: "https://m040601.github.io/purejekyllgithubdefaults"
# needed
baseurl: "/purejekyllgithubdefaults"
