#theme: jekyll-theme-slate

#GitHub Pages supports the following themes:
#    Architect
#    Cayman
#    Dinky
#    Hacker
#    Leap day
#    Merlot
#    Midnight
#    Minima,It's Jekyll's default (and first) theme. It's what you get when you run jekyll new.
#    Minimal, theme: jekyll-theme-minimal ????
#    Modernist
#    Slate
#    Tactile
#    Time machine

#works
#theme: minima
#theme: jekyll-theme-minimal

#does not work
#theme: minimal


#works

# does not work
#remote_theme: "daattali/beautiful-jekyll"
#remote_theme: "Gaohaoyang/gaohaoyang.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# not needed ?
url: "https://m040601.github.io/purejekyllgithubdefaults"
# needed
baseurl: "/purejekyllgithubdefaults"


# social links
twitter_username: todaviasomos
github_username:  m040601
rss: rss
# dribbble_username: jekyll
facebook_username: todaviasociacion
flickr_username: todaviasostenible
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
youtube_username: UCDf_rncabeuc7WcrzqqLCrg
# googleplus_username: +jekyll



description: > # this means to ignore newlines until "twitter_username:"
  If i leave "description" empty in config.yaml, it picks up the one frome github



# prose stufzzz
# https://github.com/prose/prose/wiki/Getting-Started

#For non-jekyll sites, You can set up configurations by creating a _prose.yml file 
#or add configurations as an entry to your Jekyll site in _config.yml.

An example configuration looks like this:

prose:
  # restrict to only _posts
  # rooturl: '_posts'
  siteurl: 'https://m040601.github.io/purejekyllgithubdefaults'

  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  #media: 'media'
  ignore:
    - index.md
    - _config.yml
    # - /_drafts
    - /_layouts
    - /_includes
    # - /docs
    - another_page.md
    - page-embed-share.md
    #- page-no-layout-but-h1.md
    #- page-no-layout-but-h2.md
    #- page-no-layout-but-h3.md
    - page-no-title-layout-page-h1-content.md
    - page-only-title-sorry.md
    - page-with-absolutely-nothing.md
    - page-with-only-raw-text.md
  
  
  metadata:
    _posts:
    
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Vananas"
              value: "wananas"
            - name: "oananas"
              value: "oananas"
            - name: "iananas"
              value: "iananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""

theme: jekyll-theme-cayman